### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by IvoryTower152** [Impression2805/IL2A#1]
Thank you very much for the code base!
I am having troubles reproducing the results in the paper. In section 3.1.1 of the paper, you introduced a spectral decomposition method for analyzing forgetting.  But I got confused about the format of the deep features,  I want to know whether it is a feature directly obtained in a feature extractor (like [160, 4, 4]) or a feature vector after flattening (like [2560, ]). 
It would be great  if you could provide some more details on the above issues.
Thank you very much!

**Comment by Impression2805** [comment]
Sorry for the late reply. The deep features refer to the feature vectors after flattening. In our experiments, the ResNet-18 is used and therefore the dimensionality of the final feature vectors is 512.

Closing for now, feel free to get in touch again if there's still problems.
