### ISSUE TITLE
Reproducing

### ISSUE THREAD

**Issue by mercury-w** [Impression2805/IL2A#2]
Hi, Thank you very much for the code base!
I am reproducing this article using the cifar100 dataset without making any changes to the code on this github, why the results are a bit different from your paper, do I need to adjust some parameters?
It would be great if you could solve my problem, thanks!

**Comment by Impression2805** [comment]
Thank you for your interest in our paper. We have discussed this issue before via email, and the devil is the torch/python version. The results can be successfully reproduced with torch version 1.10.0 and python version 3.9.7.
